apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: simple-buy
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
